library(dplyr)
library(ggplot2)
library(fitdistrplus)
library(lme4)
library(scales)
library(rprojroot)

MWROOT <- is_rstudio_project$make_fix_file()
source(MWROOT("includes","mwMod.R"))
source(MWROOT("includes","mwIPM.R"))