theme: jekyll-theme-cayman
title: Source code for paper...
description: Herbivory decreases population growth of common milkweed (Asclepias syriaca) through negative effects on clonal reproduction
show_downloads: true
