theme: jekyll-theme-modernist
title: Herbivory decreases population growth of common milkweed (Asclepias syriaca) through negative effects on clonal reproduction
description: This repository contains the code for the above publication as an RStudio Project.
