---
title: "Supplement - Parameter Tables"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
---

# Initialization

```{r}
library(milkweed)
library(dplyr)
library(tidyr)
library(ggplot2)
library(flextable)
library(webshot)
library(boot)
library(kable)
library(kableExtra)
```

# Distribution Parameters

```{r}
# Cardenolides
load(here::here('data/mwCache/cardenolideDistFit.RData'))
CI <- unname(summary(fitdistrplus::bootdist(card.fit$fit))$CI)
df <- data.frame(Model = rep("Cardenolides",2),
           Parameter = c("$\\mu$", "$\\sigma$"),
           Lower = CI[,2],
           Value = unname(card.fit$fit$estimate),
           Upper = CI[,3])

# LMA
load(here::here('data/mwCache/lmaDistFit.RData'))
CI <- unname(summary(fitdistrplus::bootdist(lma.fit$fit))$CI)
df <- rbind(df,
  data.frame(Model = rep("LMA",2),
           Parameter = c("$\\mu$", "$\\sigma$"),
           Lower = CI[,2],
           Value = unname(lma.fit$fit$estimate),
           Upper = CI[,3])
)

# Herbivory
load(here::here('data/mwCache/herbivoryDistFit.RData'))
CI <- unname(summary(fitdistrplus::bootdist(munched.fit$fit))$CI)
df <- rbind(df,
  data.frame(Model = rep("Herbivory", 3),
           Parameter = c("$p_{\\omega}$", "$\\mu$", "$\\sigma$"),
           Lower = c(NA, CI[,2]),
           Value = c(munched.fit$pmunch, unname(munched.fit$fit$estimate)),
           Upper = c(NA, CI[,3]))
)

# Sprout Recruit Height
load(here::here('data/mwCache/budlingDistFit.RData'))
CI <- unname(summary(fitdistrplus::bootdist(budling.fit$fit))$CI)
df <- rbind(df,
  data.frame(Model = rep("Sprout Recruit Height",2),
           Parameter = c("$\\mu$", "$\\sigma$"),
           Lower = CI[,2],
           Value = unname(budling.fit$fit$estimate),
           Upper = CI[,3])
)

# Seedling Recruit Height
load(here::here('data/mwCache/seedlingDistFit.RData'))
CI <- unname(summary(fitdistrplus::bootdist(seedling.fit$fit))$CI)
df <- rbind(df,
  data.frame(Model = rep("Seedling Recruit Height",2),
           Parameter = c("$\\mu$", "$\\sigma$"),
           Lower = CI[,2],
           Value = unname(seedling.fit$fit$estimate),
           Upper = CI[,3])
)

kable(df, "latex", booktabs = T, align = "c", escape = F, digits = 3, col.names = c("Variable", "Parameter", "$2.5\\%$", "Value", "$97.5\\%$")) %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  kable_as_image(keep_pdf = TRUE)
```

# Model Parameters

```{r}
# Flowering
load(here::here('data/mwCache/flowerFit.RData'))
CI <- unname(confint(flower.fit$mdl))
df <- data.frame(Model = rep("Flowering",4),
           Parameter = c("$\\alpha$", "$\\beta_{z_{h}}$", "$\\beta_{z_{\\omega}}$", "$\\beta_{z_{c}}$"),
           Lower = formatC(CI[,1], format="f", digits=3),
           Value = formatC(unname(flower.fit$mdl$coefficients), format="f", digits=3),
           Upper = formatC(CI[,2], format="f", digits=3))

# Survival
load(here::here('data/mwCache/survivalFit.RData'))
CI <- unname(confint(surv.fit$mdl))
df <- rbind(df,
            data.frame(Model = rep("Survival", 5),
                       Parameter = c("$\\alpha$", "$\\beta_{z_{h}}$", "$\\beta_{z_{\\omega}}$", "$\\beta_{z_{c}}$", "$\\beta_{z_{l}}$"),
                       Lower = formatC(CI[,1], format="f", digits=3),
                       Value = formatC(unname(surv.fit$mdl$coefficients), format="f", digits=3),
                       Upper = formatC(CI[,2], format="f", digits=3))
)

# Pods
load(here::here('data/mwCache/podsFit.RData'))
CI <- unname(confint(pods.fit$mdl))
df <- rbind(df,
            data.frame(Model = rep("Pods", 5),
                       Parameter = c("$\\alpha$", "$\\beta_{z_{h}}$", "$\\beta_{z_{\\omega}}$", "$\\beta_{z_{c}}$", "$\\beta_{z_{l}}$"),
                       Lower = formatC(CI[,1], format="f", digits=3),
                       Value = formatC(unname(pods.fit$mdl$coefficients), format="f", digits=3),
                       Upper = formatC(CI[,2], format="f", digits=3))
)

# Seeds per pod
result <- t.test(seeddata$total_seed)
df <- rbind(df,
            data.frame(Model = "Seeds per Pod",
                       Parameter = "$\\alpha$",
                       Lower = formatC(unname(result$conf.int[1]), format="f", digits=3),
                       Value = formatC(unname(result$estimate), format="f", digits=3),
                       Upper = formatC(unname(result$conf.int[2]), format="f", digits=3))
)

# Seedling Recruitment
load(here::here("data/mwCache/seedlingEmergenceConst.RData"))
compute = FALSE
if (compute) {
  all_sites = c("Bertha", levels(stemdata$site))
  N = 6000 # https://stats.stackexchange.com/questions/37918/why-is-the-error-estimated-adjustment-a-is-na-generated-from-r-boot-package
  # Get bootstrapped seed data needed for emergence
  stem_stat_func <- function(x, ind) { 
    seed_stat_func <- function(x, ind) { mean(x[ind]) }
    seeds.per.pod <- boot(seeddata$total_seed, seed_stat_func, R = 1)$t  # Not efficient but easy
    
    data_gp <- x[ind,] %>% group_by(year) %>% summarize(N_seedlings = sum(seedling, na.rm=T),
                                                        N_seeds = seeds.per.pod*sum(N_pods, na.rm=T))
    
    mean(data_gp$N_seedlings[1:nrow(data_gp)-1]/data_gp$N_seeds[2:nrow(data_gp)], na.rm=T)
  } 
  bs <- boot(stemdata, stem_stat_func, R = N)
  bs.ci <- boot.ci(bs)
  save(list = c("bs", "bs.ci"), file = here::here("data/mwCache/seedlingEmergenceConstBS.RData"))
} else {
  load(here::here("data/mwCache/seedlingEmergenceConstBS.RData"))
}
df <- rbind(df,
            data.frame(Model = "Seedling Recruitment",
                       Parameter = "$\\alpha$",
                       Lower = formatC(bs.ci$percent[4], format="f", digits=6),
                       Value = formatC(seedling.emergence, format="f", digits=6),
                       Upper = formatC(bs.ci$percent[5], format="f", digits=6))
)

# Clonal Reproduction
load(here::here("data/mwCache/budlingsPerStemFit.RData"))
CI <- unname(confint(budlings.per.stem.fit$fit))
df <- rbind(df,
            data.frame(Model = rep("Clonal Reproduction", 2),
                       Parameter = c("$\\alpha$", "$\\beta_{z_{c}}$"),
                       Lower = formatC(CI[,1], format="f", digits=3),
                       Value = formatC(unname(budlings.per.stem.fit$fit$coefficients), format="f", digits=3),
                       Upper = formatC(CI[,2], format="f", digits=3))
)

kable(df, "latex", booktabs = T, align = "c", escape = F, col.names = c("Model", "Parameter", "$2.5\\%$", "Value", "$97.5\\%$")) %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  kable_as_image(keep_pdf = TRUE)
```
