---
title: "Fit Budling Distribution"
author: "M. Drew LaMar"
date: "May 23, 2016"
output: 
  html_document:
    toc: true
---

We use the `fdistrplus` package (https://cran.r-project.org/web/packages/fitdistrplus/vignettes/paper2JSS.pdf)

```{r, warning=FALSE, message=FALSE}
library(fitdistrplus)
library(dplyr)
library(lattice)
```

Read, filter and transform data.
```{r}
metadata=tbl_df(read.csv("~/Google Drive/Project :: ipmwam/Papers/SivansPaper/Milkweed/DATA SETS/Data Frames/metadata13to15.csv"))

metadat <- metadata %>% mutate(seedling = ifelse(is.na(stem_width),NA,ifelse(stem_width <= 2.0,1,0))) %>% 
                        filter(!is.na(h_apical),
                                !is.na(h_apical.next),
                                !is.na(herb_avg),
                                !is.na(fec.flower),
                                !is.na(surv),
                                h_apical.next > 50,
                                !(site == "YTB" & h_apical <= 50))
```

# Bertha

Fits of h_apical for budlings.
```{r}
h_apical <- (metadat %>% filter(seedling == 0))$h_apical

f0 <- fitdist(h_apical, "norm")
f1 <- fitdist(h_apical, "lnorm")
f2 <- fitdist(h_apical, "gamma")
f3 <- fitdist(h_apical, "exp")
f4 <- fitdist(h_apical, "weibull")
```

Plot results.
```{r}
par(mfrow=c(2,2))
plot.legend <- c("normal", "lognormal", "gamma", "exp", "weibull")
denscomp(list(f0, f1, f2, f3, f4), legendtext = plot.legend)
cdfcomp(list(f0, f1, f2, f3, f4), legendtext = plot.legend)
qqcomp(list(f0, f1, f2, f3, f4), legendtext = plot.legend)
ppcomp(list(f0, f1, f2, f3, f4), legendtext = plot.legend)
par(mfrow=c(1,1))
```

Goodness-of-fit measures.
```{r}
gofstat(list(f0, f1, f2, f3, f4), fitnames = plot.legend)
```

Here are the estimates.
```{r}
sites <- c("Bertha", "BLD1", "BLD2", "PWR", "SKY", "YTB")
budling.fit <- vector('list', 6)
names(budling.fit) <- sites

budling.fit[['Bertha']] <- vector("list", 2)
budling.fit[['Bertha']][[1]] <- f0

# Two ways to take care of missing probability.  Choosing to spread as opposed to adding to endpoints.  Other technique commented out here.
#  y[1] <- y[1] + p%s(x[1], %g, %g)
#  y[N] <- y[N] + p%s(x[N], %g, %g, lower.tail=FALSE)
budling.fit[['Bertha']][[2]] <- eval(parse(text = sprintf("function(x) {
  N <- length(x)
  dx <- x[2]-x[1]  
  y <- rep(0, N-1)
  for (j in 1:(N-1)) {
    y[j] = p%s(x[j+1], %g, %g) - p%s(x[j], %g, %g)
  }
  y <- y/(dx*sum(y))
  }", budling.fit[[1]][[1]]$distname, budling.fit[[1]][[1]]$estimate[1], budling.fit[[1]][[1]]$estimate[2], 
  budling.fit[[1]][[1]]$distname, budling.fit[[1]][[1]]$estimate[1], budling.fit[[1]][[1]]$estimate[2]
  )))
names(budling.fit[['Bertha']]) <- c("fit", "predict")
```

Plot results to make sure I know what I'm doing.
```{r}
x <- seq(from=0, to=160, length.out=100)
y <- budling.fit[['Bertha']]$predict(x)

hist(h_apical, freq=FALSE, ylim=c(0,0.02))
lines(0.5*(x[1:99]+x[2:100]),y,col='red')
```

# Sites

First, loop through to get best fits.
```{r}
for (i in 2:6) {
  h_apical <- (metadat %>% filter(seedling == 0, site == sites[i]))$h_apical

  f0 <- fitdist(h_apical, "norm")
  f1 <- fitdist(h_apical, "lnorm")
  f2 <- fitdist(h_apical, "gamma")
  f3 <- fitdist(h_apical, "exp")
  f4 <- fitdist(h_apical, "weibull")
  
  ind <- which.min(gofstat(list(f0, f1, f2, f3, f4))$aic)
  
  budling.fit[[i]] <- vector("list", 2)
  eval(parse(text=sprintf("budling.fit[[%d]][[1]] <- f%d", i, ind-1)))
  budling.fit[[i]][[2]] <- eval(parse(text = sprintf("function(x) {
  N <- length(x)
  dx <- x[2]-x[1]  
  y <- rep(0, N-1)
  for (j in 1:(N-1)) {
    y[j] = p%s(x[j+1], %g, %g) - p%s(x[j], %g, %g)
  }
  y <- y/(dx*sum(y))
  }", budling.fit[[i]][[1]]$distname, budling.fit[[i]][[1]]$estimate[1], budling.fit[[i]][[1]]$estimate[2], 
  budling.fit[[i]][[1]]$distname, budling.fit[[i]][[1]]$estimate[1], budling.fit[[i]][[1]]$estimate[2]
  )))
  names(budling.fit[[i]]) <- c("fit", "predict")
  cat("\n-------\n")
  cat(sites[i], "\n")
  print(budling.fit[[sites[i]]])
}
```

Let's plot these using a trellis plot.
```{r}
metadat_buds <- metadat %>% filter(seedling == 0)
histogram(~ h_apical|site, data=metadat_buds, type = c("density"), budling.fit = budling.fit, panel = function(x,y) {
  panel.histogram(x, breaks=10)
  myx <- seq(from = 0, to = 160, length.out = 100)
  i <- packet.number()+1
  myy <- budling.fit[[i]]$predict(myx)
  panel.lines(0.5*(myx[1:99]+myx[2:100]), myy, col="red", lwd=2)
})
```

Save results to file.
```{r}
save(budling.fit, file = "budlingFit.RData")
```