---
title: "Get Seedling Emergence"
author: "M. Drew LaMar"
date: "June 11, 2016"
output: html_document
---

Right now, just use Sivan's already calculated values.  Will double-check later.

Load previously computed values from 5 sites.
```{r}
load("~/Google Drive/Project :: ipmwam/Milkweed/DATA SETS/Variables/bld1SEE.csv") #object: bld1.SEE (SEE: sdlg establishment & emergence)

load("~/Google Drive/Project :: ipmwam/Milkweed/DATA SETS/Variables/bld2SEE.csv") #object: bld2.SEE (SEE: sdlg establishment & emergence)

load("~/Google Drive/Project :: ipmwam/Milkweed/DATA SETS/Variables/pwrSEE.csv") #object: pwr.SEE (SEE: sdlg establishment & emergence)

load("~/Google Drive/Project :: ipmwam/Milkweed/DATA SETS/Variables/skySEE.csv") #object: sky.SEE (SEE: sdlg establishment & emergence)

load("~/Google Drive/Project :: ipmwam/Milkweed/DATA SETS/Variables/ytbSEE.csv") #object: ytb.SEE (SEE: sdlg establishment & emergence)
```

Store in different combined format.
```{r}
sites <- c("Bertha", "BLD1", "BLD2", "PWR", "SKY", "YTB")
seedling.emergence <- rep(0,6)
seedling.emergence[2:6] <- c(bld1.SEE, bld2.SEE, pwr.SEE, sky.SEE, ytb.SEE)

# For now, Bertha is average
seedling.emergence[1] <- mean(seedling.emergence[2:6])

names(seedling.emergence) <- sites
```

Save to file.
```{r}
save(seedling.emergence, file = "seedlingEmergence.RData")
```