---
title: "Bootstrap"
author: "Soren Struckman"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

# Initialization

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(milkweed)
library(dplyr)
library(ggplot2)

'%<>%' <- magrittr::'%<>%'
TeX <- latex2exp::TeX

#ipm = mwIPM(list(compute = T, saveresults = FALSE))
mwCache <- '../../data/mwCache'
```

# Analysis

## Bootstrap

The function should save a piece of what we need to generate the caterpillar plot and confidence intervals around elasticities, as well as a confidence interval around lambda... every time it is run. Then they can all be put together into one data frame.
```{r}
bootstrap = function(ipm, runs = 1) {
  results = data.frame()
  for(i in 1:runs) {
    tmp = ipm %>% bootIPM() %>% analyzeParameters(distpars = FALSE) #changed from TRUE
    results <- bind_rows(results, tmp$analysis$parameters)
  }
  save(results, file=file.path(mwCache, paste0(format(Sys.Date()), "_figure6.RData")))
}
```

```{r, echo = FALSE}
runs = 1

pracma::tic()
ipm %>% bootstrap(runs = runs)
pracma::toc(echo=T)
```

```{r, echo = FALSE}
ipm = mwIPM(list(compute = T, saveresults = FALSE)) %>% bootIPM()
tmp = ipm %<>% analyzeParameters(distpars = FALSE) #changed from TRUE
results <- tmp$analysis$parameters
save(results, file=file.path(mwCache, paste0(format(Sys.Date()), "_figure6.RData")))
```

#Lambda by itself
```{r, echo=FALSE}
ipm = mwIPM(list(compute = T, saveresults = FALSE))

runs = 50
lambdas = c()
pracma::tic()
for(i in 1:runs) {
    tmp = ipm %>% bootIPM() %>% analyzeGrowthRate()
    lambdas <- c(lambdas, tmp)
}
pracma::toc()

save(lambdas, file=file.path("/Users/slstruckman_admin/traits/data/mwCache", 'lambdas_storage.RData'))
```

```{r}
lamb = lambdas
results = data.frame(lambda = lamb) %>% summarize(n = n(),
                                                  mean_lamb = mean(lambda),
                                                  se = sd(lambda)/sqrt(n),
                                                  ci = qt(0.975, n-1)*se)
```

