---
title: "Figure 4: Clonal growth versus herbivory"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(milkweed)
library(dplyr)
library(ggplot2)
ipm <- mwIPM(list(compute = TRUE, saveresults = TRUE))
fit <- ipm$pars$budlings.per.stem.fit$fit
```

# Budlings-per-stem

Let's start with just the data points.

```{r, warning=FALSE, message=FALSE}
merged <- fit$data

plotdata <- data.frame(herb_avg = merged$herb_mean, 
                       buds_per_stem = merged$bdlgs_per_stem,
                       site = merged$site)

p <- plotdata %>% ggplot(aes(x = herb_avg, 
                             y = buds_per_stem,
                             color = site)) + 
                  geom_point()

p
```

Let's add the fit.

```{r, warning=FALSE, message=FALSE, eval=FALSE}
xpts <- seq(from=min(merged$herb_mean), to=max(merged$herb_mean), length.out = 100)

# http://www.remkoduursma.com/post/2017-06-15-bootpredictlme4/
# https://cran.r-project.org/web/packages/merTools/vignettes/Using_predictInterval.html
# Confidence intervals for GLMMs
ypts <- lme4::bootMer(ipm$pars$budlings.per.stem.fit$mdl, nsim=1000, 
                      FUN=function(x)predict(x, newdata=data.frame(herb_mean = xpts), type="response", re.form=NA))

plotdata <- data.frame(herb_avg = xpts, 
                       buds_per_stem = apply(ypts$t, 2, FUN=function(x) mean(x, na.rm=TRUE)),
                       lwr = apply(ypts$t, 2, FUN=function(x) quantile(x, 0.025, na.rm=TRUE)),
                       upr = apply(ypts$t, 2, FUN=function(x) quantile(x, 0.975, na.rm=TRUE)),
                       site = NA)

summary(ipm$pars$budlings.per.stem.fit$fit)


p <- p + geom_line(data = plotdata, 
                   color = "black", 
                   linetype = "solid") +
         geom_ribbon(data = plotdata, 
                     aes(ymin=lwr, 
                         ymax=upr), 
                     alpha = 0.2) # + 
         # scale_y_continuous(limits = c(0, 3.5))
         
p <- p + theme_bw() +
         xlab("Herbivory severity") +
         ylab("Per capita clonal reproduction\n (sprouts/stem)") +
         labs(color="Sites") + 
         # scale_x_continuous(limits = c(0.0, 2.0)) + 
         theme(legend.background = element_rect(fill="lightgrey",
                                                size=0.1,
                                                linetype="solid"),
               legend.key.size =  unit(0.2, "in"),
               legend.position = c(0.875, 0.75))

p
```

```{r, warning=FALSE, message=FALSE}
xpts <- seq(from=0, to=2, length.out = 1000)

# https://fromthebottomoftheheap.net/2018/12/10/confidence-intervals-for-glms/
# Correct way to compute confidence intervals for GLMs (predict on link scale, the default, and then linkinv)

ilink <- family(fit)$linkinv
ypts <- predict(fit, newdata=data.frame(herb_mean = xpts), se.fit = TRUE)

plotdata <- data.frame(herb_avg = xpts, 
                       buds_per_stem = ilink(ypts$fit),
                       lwr = ilink(ypts$fit - 2*ypts$se.fit),
                       upr = ilink(ypts$fit + 2*ypts$se.fit),
                       site = NA)

p <- p + geom_line(data = plotdata, 
                   color = "black", 
                   linetype = "solid") +
         geom_ribbon(data = plotdata, 
                     aes(ymin=lwr, 
                         ymax=upr), 
                     alpha = 0.2) + 
         scale_y_continuous(limits = c(0, 3.0))
         
p <- p + theme_bw() +
         xlab("Herbivory severity") +
         ylab("Per capita clonal reproduction\n (sprouts/stem)") +
         labs(color="Sites") + 
         scale_x_continuous(limits = c(0.0, 2.0)) + 
         theme(legend.background = element_rect(fill="lightgrey",
                                                size=0.1,
                                                linetype="solid"),
               legend.key.size =  unit(0.2, "in"),
               legend.position = c(0.875, 0.75))

p
```



Save figure.

```{r}
ggsave("Figure4_ClonalGrowthVsHerb.png", height=4, width=6, device = "png", p)
```
