---
title: "Fit Seedling Distribution"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

We use the `fdistrplus` package (https://cran.r-project.org/web/packages/fitdistrplus/vignettes/paper2JSS.pdf)

```{r, warning=FALSE, message=FALSE}
library(milkweed)
library(fitdistrplus)
library(dplyr)
library(magrittr)
sites <- c("Bertha", "BLD", "PWR", "SKY", "YTB")
```

Read, filter and transform data.
```{r}
data("stemdata")
metadata <- dem.data
```

Fits of h_apical for seedlings.
```{r}
h_apical <- metadata %>% 
  filter(seedling == 1,
         !is.na(h_apical)) %$%
  h_apical

distnames <- c("norm", "lnorm", "gamma", "exp", "weibull")

f0 <- fitdist(h_apical, distnames[1])
f1 <- fitdist(h_apical, distnames[2])
f2 <- fitdist(h_apical, distnames[3]) #produces some NaNs
f3 <- fitdist(h_apical, distnames[4])
f4 <- fitdist(h_apical, distnames[5]) #produces some NaNs
```

Plot results.
```{r}
plot_diagnostics <- function(...) {
  par(mfrow=c(2,2))
  denscomp(list(...), legendtext = distnames)
  cdfcomp(list(...), legendtext = distnames)
  qqcomp(list(...), legendtext = distnames)
  ppcomp(list(...), legendtext = distnames)
  par(mfrow=c(1,1))
}

plot_diagnostics(f0, f1, f2, f3, f4)
```

Goodness-of-fit measures.
```{r}
gofstat(list(f0, f1, f2, f3, f4), fitnames = distnames)
```

Weibull and normal are indistinguishable. So let's go with normal for ease of analysis.
