---
title: "Figure 3: Clonal growth versus herbivory"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
source("../../../.Rprofile")
ipm <- mwIPM()
```

# Budlings-per-stem

Let's start with just the data points.

```{r, warning=FALSE, message=FALSE}
attach(ipm$pars)
plotdata <- data.frame(log_herb_avg = budlings.per.stem.fit$fit$model$log_herb_mean, 
                       buds_per_stem = exp(budlings.per.stem.fit$fit$model$`log(bdlgs_per_stem)`),
                       site = budlings.per.stem.fit$site)

p <- plotdata %>% ggplot(aes(x = log_herb_avg, 
                             y = buds_per_stem,
                             color = site)) + 
                  geom_point()

p
detach(ipm$pars)
```

Let's add the fit.

```{r, warning=FALSE, message=FALSE}
attach(ipm$pars)
xpts <- seq(from=log(0.1), to=log(6.1), length.out = 1000)
ypts <- predict(budlings.per.stem.fit$fit, 
                new = data.frame(log_herb_mean = xpts), 
                level=0.95,
                interval="confidence",
                se.fit=TRUE)
plotdata <- data.frame(log_herb_avg = xpts, 
                       buds_per_stem = exp(ypts$fit[,"fit"]),
                       lwr = exp(ypts$fit[,"lwr"]),
                       upr = exp(ypts$fit[,"upr"]),
                       site = NA)

p <- p + geom_line(data = plotdata, 
                   color = "black", 
                   linetype = "solid") +
         geom_ribbon(data = plotdata, 
                     aes(ymin=lwr, 
                         ymax=upr), 
                     alpha = 0.2) + 
         scale_y_continuous(limits = c(0, 2.8))
         
p <- p + theme_bw() +
         xlab("ln(Herbivory Score)") +
         ylab("Per capita clonal reproduction\n (sprouts/stem)") +
         labs(color="Sites") + 
         theme(legend.background = element_rect(fill="lightgrey",
                                                size=0.1,
                                                linetype="solid"),
               legend.key.size =  unit(0.2, "in"),
               legend.position = c(0.875, 0.65))

p
detach(ipm$pars)
```

Save figure.

```{r}
ggsave("Figure3.png", height=4, width=6, device = "png", p)
```