---
title: "PCA"
author: "Joshua Mutterperl"
date: "2023-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
```


```{r}
ids_to_remove <- c("3140","4043")

milkweedData <- read.csv("demo_data_with_genetid.csv")

numberData <- filter(milkweedData, !(milkweedData$plantID %in% ids_to_remove)) 
# also filter out !(is.na(milkweedData$h_apical_next)), (milkweedData$h_apical_next != ""), (milkweedData$h_apical_next != "ND") for h_apical_next

numberData$h_apical <- as.numeric(numberData$h_apical) # change to h_apical_next

numberData <- dplyr::select_if(numberData, is.numeric)

numberData <- na.omit(numberData)

milkweedData <- subset(milkweedData, plantID %in% numberData$plantID)

numberData <- numberData %>% select_at(vars(h_apical, l_length, l_width, stem_width, N_leaves)) # change h_apical to h_apical_next for h2

results <- prcomp(numberData, scale = TRUE)

results$rotation <- -1*results$rotation

results$rotation

results$x <- -1*results$x
head(results$x)
str(results$x[,1])
milkweedData$pc1 <- results$x[,1]
write.csv(milkweedData, "demo_data_with_genetid_h1.csv") # change file name for h2
```
